###############################################################################################
# mens
###############################################################################################

MENS_STRAWWEIGHT = 'mens strawweight'  # 52.5kg

MENS_FLYWEIGHT = 'mens flyweight'  # 56.7kg

MENS_BANTAMWEIGHT = 'mens bantamweight'  # 61.2kg
ALJAMAIN_STERLING = 'Aljamain Sterling'
ANDERSON_BERLINGERI_DOS_SANTOS = 'Anderson Berlingeri dos Santos'
ANDRE_EWELL = 'Andre Ewell'
BEA_MALECKI = 'Bea Malecki'
CARLOS_HUACHIN_QUIROZ = 'Carlos Huachin Quiroz'
EDDIE_WINELAND = 'Eddie Wineland'
EDUARDA_SANTANA = 'Eduarda Santana'
GRIGORY_POPOV = 'Grigory Popov'
HENRY_CEJUDO = 'Henry Cejudo'
JIMMIE_RIVERA = 'Jimmie Rivera'
MARLON_MORAES = 'Marlon Moraes'
PEDRO_MUNHOZ = 'Pedro Munhoz'
PETR_YAN = 'Petr Yan'
RAONI_BARCELOS = 'Raoni Barcelos'

MENS_FEATHERWEIGHT = 'mens featherweight'  # 65.8kg
ALEXANDER_VOLKANOVSKI = 'Alexander Volkanovski'
CHAN_SUNG_JUNG = 'Chan Sung Jung'
CHRIS_FISHGOLD = 'Chris Fishgold'
DAN_IGE = 'Dan Ige'
DANIEL_TEYMUR = 'Daniel Teymur'
GRANT_DAWSON = 'Grant Dawson'
JOSE_ALDO = 'Jose Aldo'
JULIAN_EROSA = 'Julian Erosa'
JULIO_ACRE = 'Julio Acre'
KEVIN_AGUILAR = 'Kevin Aguilar'
MAKWAN_AMIRKHANI = 'Makwan Amirkhani'
MICHAEL_TRIZANO = 'Michael Trizano'
RENATO_MOICANO = 'Renato Moicano'
SUNG_BIN_JO = 'Sung Bin Jo'

MENS_LIGHTWEIGHT = 'mens lightweight'  # 70.3kg
AUSTIN_HUBBARD = 'Austin Hubbard'
BJ_PENN = 'BJ Penn'
CALVIN_KATTAR = 'Calvin Kattar'
CHARLES_JOURDAIN = 'Charles Jourdain'
CHARLES_OLIVEIRA = 'Charles Oliveira'
CHRISTOS_GIAGOS = 'Christos Giagos'
CLAY_GUIDA = 'Clay Guida'
DAMIR_HADZOVIC = 'Damir Hadzovic'
DANILO_BELLUARDO = 'Danilo Belluardo'
DAVI_RAMOS = 'Davi Ramos'
DESMOND_GREEN = 'Desmond Green'
DONALD_CERRONE = 'Donald Cerrone'
FRANK_CAMACHO = 'Frank Camacho'
JOEL_ALVAREZ = 'Joel Alvarez'
KURT_HOLOBAUGH = 'Kurt Holobaugh'
LEONARDO_SANTOS = 'Leonardo Santos'
LUIS_PENA = 'Luis Pena'
MATT_WIMAN = 'Matt Wiman'
NICK_HEIN = 'Nick Hein'
NIK_LENTZ = 'Nik Lentz'
RICARDO_LAMAS = 'Ricardo Lamas'
STEVIE_RAY = 'Stevie Ray'
THIAGO_MOISES = 'Thiago Moises'
TONY_FERGUSON = 'Tony Ferguson'

MENS_WELTERWEIGHT = 'mens welterweight'  # 77.1kg
BRYAN_BARBERENA = 'Bryan Barberena'
DANNY_ROBERTS = 'Danny Roberts'
DERRICK_KRANTZ = 'Derrick Krantz'
KEVIN_LEE = 'Kevin Lee'
LAUREANO_STAROPOLI = 'Laureano Staropoli'
MICHEL_PEREIRA = 'Michel Pereira'
RAFAEL_DOS_ANJOS = 'Rafael dos Anjos'
RANDY_BROWN = 'Randy Brown'
ROSTEM_AKMAN = 'Rostem Akman'
SERGEY_KHANDOZHKO = 'Sergey Khandozhko'
SERGIO_MORAES = 'Sergio Moraes'
THIAGO_ALVES = 'Thiago Alves'
VICENTE_LUQUE = 'Vicente Luque'
WARLLEY_ALVES = 'Warlley Alves'

MENS_MIDDLEWEIGHT = 'mens middleweight'  # 83.9kg
ALESSIO_DI_CHRICO = 'Alessio di Chirico'
ANDERSON_SILVA = 'Anderson Silva'
ANTONIO_CARLOS_JUNIOR = 'Antonio Carlos Junior'
BEVON_LEWIS = 'Bevon Lewis'
DARREN_STEWART = 'Darren Stewart'
DERON_WINN = 'Deron Winn'
ERIC_SPICELY = 'Eric Spicely'
IAN_HEINISCH = 'Ian Heinisch'
JARED_CANNONIER = 'Jared Cannonier'
KEVIN_HOLLAND = 'Kevin Holland'
TREVIN_GILES = 'Trevin Giles'
ZAK_CUMMINGS = 'Zak Cummings'

MENS_LIGHT_HEAVYWEIGHT = 'mens light heavyweight'  # 93kg
ALEKSANDAR_RAKIC = 'Aleksandar Rakic'
ALEXANDER_GUSTAFSSON = 'Alexander Gustafsson'
ANTHONY_SMITH = 'Anthony Smith'
ANTONIO_ROGERIO_NOGUEIRA = 'Antonio Rogerio Nogueira'
DARKO_STOSIC = 'Darko Stosic'
DEVIN_CLARK = 'Devin Clark'
ED_HERMAN = 'Ed Herman'
JIMI_MANUWA = 'Jimi Manuwa'
PATRICK_CUMMINS = 'Patrick Cummins'
RYAN_SPANN = 'Ryan Spann'

MENS_HEAVYWEIGHT = 'mens heavyweight'  # 120.2kg
ALLEN_CROWDER = 'Allen Crowder'
BLAGOY_IVANOV = 'Blagoy Ivanov'
JAIRZINHO_ROZENSTRUIK = 'Jairzinho Rozenstruik'
TAI_TUIVASA = 'Tai Tuivasa'

###############################################################################################
# womans
###############################################################################################

WOMANS_STRAWWEIGHT = 'womans strawweight'
ALEXA_GRASSO = 'Alexa Grasso'
ANGELA_HILL = 'Angela Hill'
ASHLEY_YODER = 'Ashley Yoder'
JESSICA_ANDRADE = 'Jessica Andrade'
KAROLINA_KOWALKIEWICZ = 'Karolina Kowalkiewicz'
NINA_ANSAROFF = 'Nina Ansaroff'
ROSE_NAMAJUNAS = 'Rose Namajunas'
SYURI_KONDO = 'Syuri Kondo'
TATIANA_SUAREZ = 'Tatiana Suarez'
XIAONAN_YAN = 'Xiaonan Yan'

WOMANS_FLYWEIGHT = 'womans flyweight'
ANDREA_LEE = 'Andrea Lee'
ARIANE_LIPSKI = 'Ariane Lipski'
JESSICA_EYE = 'Jessica Eye'
JOANNE_CALDERWOOD = 'Joanne Calderwood'
KATLYN_CHOOKAGIAN = 'Katlyn Chookagian'
LUANA_CAROLINA = 'Luana Carolina'
MOLLY_MCCANN = 'Molly McCann'
MONTANA_DE_LA_ROSA = 'Montana de la Rosa'
PRISCILA_CACHOEIRA = 'Priscila Cachoeira'
VALENTINA_SHEVCHENKO = 'Valentina Shevchenko'

WOMANS_BANTAMWEIGHT = 'womans bantamweight'
ASPEN_LADD = 'Aspen Ladd'
BETHE_CORREIA = 'Bethe Correia'
IRENE_ALDANA = 'Irene Aldana'
LINA_LANSBERG = 'Lina Lansberg'
SIJARA_EUBANKS = 'Sijara Eubanks'
TALITA_BERNARDO = 'Talita Bernardo'
TONYA_EVINGER = 'Tonya Evinger'
VIVIANE_ARAUJO = 'Viviane Araujo'

WOMANS_FEATHERWEIGHT = 'womans featherweight'
FELICIA_SPENCER = 'Felicia Spencer'
MEGAN_ANDERSON = 'Megan Anderson'
