from datetime import datetime, timedelta

from men import *

RH = 'Right-Handed'
LH = 'Left-Handed'
OHB = 'One-Handed Backhand'
THB = 'Two-Handed Backhand'


def get_age_months(player):
    age = get_born_at(player)
    delta = datetime.now() - age
    return delta.days / 30


def get_born_at(player):
    meta = META[player]
    if 'born_at' in meta:
        return datetime(*meta['born_at'])
    return avg_born_at


def get_default_metas():
    born_ats = []
    for player in META:
        if 'born_at' in META[player]:
            born_ats.append(datetime(*META[player]['born_at']))
    avg_date = avg(born_ats)
    return avg_date


def avg(dates):
    any_reference_date = datetime(1900, 1, 1)
    time_deltas = [date - any_reference_date for date in dates]
    return any_reference_date + sum(time_deltas, timedelta()) / len(dates)


META = {
    ADAM_EL_MIHDAWY: {
        'born_at': (1989, 8, 9),
    },
    ADAM_MOUNDIR: {
        'born_at': (1995, 4, 26),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    ADAM_PAVLASEK: {
        'born_at': (1994, 10, 8),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ADHAM_GABER: {
        'born_at': (2000, 6, 28),
        'forehand': RH,
        'backhand': THB,
    },
    ADMIR_KALENDER: {
        'born_at': (2001, 1, 12),
        'forehand': RH,
        'backhand': THB,
    },
    ADRIAN_ANDREEV: {
        'born_at': (2001, 5, 12),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    ADRIAN_BODMER: {
        'born_at': (1995, 3, 6),
        'height': 180,
        'forehand': RH,
        'backhand': OHB,
    },
    ADRIAN_MANNARINO: {
        'born_at': (1988, 6, 29),
        'height': 180,
        'forehand': LH,
        'backhand': THB,
    },
    ADRIAN_MENENDEZ_MACEIRAS: {
        'born_at': (1985, 10, 28),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    AJEET_RAI: {
        'born_at': (1999, 1, 18),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    AKIRA_SANTILLAN: {
        'born_at': (1997, 5, 22),
        'height': 180,
        'forehand': RH,
        'backhand': OHB,
    },
    ALAN_MAGADAN: {
        'born_at': (2001, 5, 26),
    },
    ALASTAIR_GRAY: {
        'born_at': (1998, 6, 22),
        'height': 188,
        'forehand': RH,
        'backhand': OHB,
    },
    ALBANO_OLIVETTI: {
        'born_at': (1991, 11, 24),
        'height': 203,
        'forehand': RH,
        'backhand': OHB,
    },
    ALBERT_RAMOS_VINOLAS: {
        'born_at': (1988, 1, 17),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    ALDIN_SETKIC: {
        'born_at': (1987, 12, 21),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    ALEJANDRO_DAVIDOVICH_FOKINA: {
        'born_at': (1999, 6, 5),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ALEJANDRO_TABILO: {
        'born_at': (1997, 6, 2),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    ALEKSANDAR_VUKIC: {
        'born_at': (1996, 4, 6),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    ALEKSANDR_NEDOVYESOV: {
        'born_at': (1987, 2, 15),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    ALEN_AVIDZBA: {
        'born_at': (2000, 2, 24),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    ALESSANDRO_GIANNESSI: {
        'born_at': (1990, 5, 30),
        'height': 185,
        'forehand': LH,
        'backhand': THB,
    },
    ALEX_BOLT: {
        'born_at': (1993, 1, 5),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    ALEX_DE_MINAUR: {
        'born_at': (1999, 2, 17),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ALEXANDAR_LAZAROV: {
        'born_at': (1997, 11, 6),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ALEXANDER_BUBLIK: {
        'born_at': (1997, 6, 17),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    ALEXANDER_ERLER: {
        'born_at': (1997, 10, 27),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    ALEXANDER_VASILENKO: {
        'born_at': (1995, 2, 26),
        'forehand': RH,
        'backhand': THB,
    },
    ALEXANDER_ZHURBIN: {
        'born_at': (1992, 1, 14),
        'forehand': LH,
    },
    ALEXANDER_ZVEREV: {
        'born_at': (1997, 4, 20),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    ALEXANDRE_MULLER: {
        'born_at': (1997, 2, 1),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    ALEXEI_POPYRIN: {
        'born_at': (1999, 8, 5),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    ALEXEY_VATUTIN: {
        'born_at': (1992, 10, 27),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    ALEXIS_GALARNEAU: {
        'born_at': (1999, 3, 2),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    ALJAZ_BEDENE: {
        'born_at': (1989, 7, 18),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ALTUG_CELIKBILEK: {
        'born_at': (1996, 9, 7),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    AMIR_WEINTRAUB: {
        'born_at': (1986, 9, 16),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ANDREA_ARNABOLDI: {
        'born_at': (1987, 12, 27),
        'height': 180,
        'forehand': LH,
        'backhand': OHB,
    },
    ANDREA_BASSO: {
        'born_at': (1993, 10, 8),
        'height': 185,
        'forehand': LH,
        'backhand': THB,
    },
    ANDREA_COLLARINI: {
        'born_at': (1992, 1, 31),
        'height': 185,
        'forehand': LH,
        'backhand': THB,
    },
    ANDREAS_SEPPI: {
        'born_at': (1984, 2, 21),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    ANDREJ_MARTIN: {
        'born_at': (1989, 9, 20),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ANDRES_MOLTENI: {
        'born_at': (1988, 3, 15),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    ANDREW_FENTY: {
    },
    ANDREW_HARRIS: {
        'born_at': (1994, 3, 7),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    ANDREY_RUBLEV: {
        'born_at': (1997, 10, 20),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    ANDY_MURRAY: {
        'born_at': (1987, 5, 15),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    ANTE_PAVIC: {
        'born_at': (1989, 3, 7),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    ANTOINE_CORNUT_CHAUVINC: {
        'born_at': (2000, 7, 7),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    ANTOINE_ESCOFFIER: {
        'born_at': (1992, 2, 29),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ANTOINE_HOANG: {
        'born_at': (1995, 11, 4),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ARJUN_KADHE: {
        'born_at': (1994, 1, 7),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ARTEM_DUBRIVNYY: {
        'born_at': (1999, 1, 31),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ARTHUR_RINDERKNECH: {
        'born_at': (1995, 7, 23),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    ASLAN_KARATSEV: {
        'born_at': (1993, 9, 4),
        'forehand': RH,
        'backhand': THB,
    },
    ATTILA_BALAZS: {
        'born_at': (1988, 9, 27),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    AUSTIN_KRAJICEK: {
        'born_at': (1990, 6, 16),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    BENJAMIN_BONZI: {
        'born_at': (1996, 6, 9),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    BENJAMIN_SIGOUIN: {
        'born_at': (1999, 6, 3),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    BENOIT_PAIRE: {
        'born_at': (1989, 5, 8),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    BERNABE_ZAPATA_MIRALLES: {
        'born_at': (1997, 1, 12),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    BERNARD_TOMIC: {
        'born_at': (1992, 10, 21),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    BJORN_FRATANGELO: {
        'born_at': (1993, 7, 19),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    BLAKE_ELLIS: {
        'born_at': (1999, 1, 6),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    BLAZ_KAVCIC: {
        'born_at': (1987, 3, 5),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    BLAZ_ROLA: {
        'born_at': (1990, 10, 5),
        'height': 193,
        'forehand': LH,
        'backhand': THB,
    },
    BORIS_FASSBENDER: {
        'born_at': (1998, 3, 20),
    },
    BORNA_CORIC: {
        'born_at': (1996, 11, 14),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    BORNA_GOJO: {
        'born_at': (1998, 2, 27),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    BRANDON_NAKASHIMA: {
        'born_at': (2001, 8, 3),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    BRAYDEN_SCHNUR: {
        'born_at': (1995, 7, 4),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    BRADLEY_KLAHN: {
        'born_at': (1990, 8, 20),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    BRADLEY_MOUSLEY: {
        'born_at': (1996, 1, 3),
        'height': 188,
        'forehand': RH,
        'backhand': OHB,
    },
    CALVIN_HEMERY: {
        'born_at': (1995, 1, 28),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    CAMERON_NORRIE: {
        'born_at': (1995, 8, 23),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    CANNON_KINGSLEY: {
        'born_at': (2001, 5, 6),
    },
    CARL_SODERLUND: {
        'born_at': (1997, 6, 3),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    CARLOS_ALCARAZ_GARFIA: {
        'born_at': (2003, 5, 5),
        'height': 183,
        'forehand': RH,
    },
    CARLOS_BERLOCQ: {
        'born_at': (1983, 2, 3),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    CARLOS_GOMEZ_HERRERA: {
        'born_at': (1990, 4, 30),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    CASPER_RUUD: {
        'born_at': (1998, 12, 22),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    CEDRIC_MARCEL_STEBE: {
        'born_at': (1990, 10, 9),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    CEM_ILKEL: {
        'born_at': (1995, 8, 21),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    CHENG_PENG_HSIEH: {
        'born_at': (1991, 9, 22),
        'height': 180,
        'forehand': LH,
        'backhand': THB,
    },
    CHUN_HSIN_TSENG: {
        'born_at': (2001, 8, 8),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    CHRISTIAN_HARRISON: {
        'born_at': (1994, 5, 29),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    CHRISTOPHER_EUBANKS: {
        'born_at': (1996, 5, 5),
        'height': 201,
        'forehand': RH,
        'backhand': OHB,
    },
    CHRISTOPHER_O_CONNELL: {
        'born_at': (1994, 6, 3),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    COLE_GROMLEY: {
    },
    COLLIN_ALTAMIRANO: {
        'born_at': (1995, 12, 7),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    CONSTANT_LESTIENNE: {
        'born_at': (1992, 5, 23),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    CORENTIN_MOUTET: {
        'born_at': (1999, 4, 19),
        'height': 175,
        'forehand': LH,
        'backhand': THB,
    },
    CHRISTIAN_GARIN: {
        'born_at': (1996, 5, 30),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    DAMIR_DZUMHUR: {
        'born_at': (1992, 5, 20),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    DANIEL_ALTMAIER: {
        'born_at': (1998, 9, 12),
        'height': 191,
        'forehand': RH,
        'backhand': OHB,
    },
    DANIEL_BRANDS: {
        'born_at': (1987, 7, 17),
        'height': 196,
        'forehand': RH,
        'backhand': OHB,
    },
    DANIEL_ELAHI_GALAN: {
        'born_at': (1996, 6, 18),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    DANIEL_EVANS: {
        'born_at': (1990, 5, 23),
        'height': 175,
        'forehand': RH,
        'backhand': OHB,
    },
    DANIEL_GIMENO_TRAVER: {
        'born_at': (1985, 8, 7),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    DANIEL_MASUR: {
        'born_at': (1994, 11, 6),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    DANIEL_NGUYEN: {
        'born_at': (1990, 10, 16),
        'height': 173,
        'forehand': RH,
        'backhand': THB,
    },
    DANIIL_MEDVEDEV: {
        'born_at': (1996, 2, 11),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    DANILO_PETROVIC: {
        'born_at': (1992, 1, 24),
        'height': 203,
        'forehand': RH,
        'backhand': THB,
    },
    DANNY_THOMAS: {
        'born_at': (1999, 11, 22),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    DARIAN_KING: {
        'born_at': (1992, 4, 26),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    DAVID_FERRER: {
        'born_at': (1982, 4, 2),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    DAVID_GOFFIN: {
        'born_at': (1990, 12, 7),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    DENIS_ISTOMIN: {
        'born_at': (1986, 9, 7),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    DENIS_KUDLA: {
        'born_at': (1992, 8, 17),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    DENIS_SHAPOVALOV: {
        'born_at': (1999, 4, 15),
        'height': 185,
        'forehand': LH,
        'backhand': OHB,
    },
    DENNIS_NOVAK: {
        'born_at': (1993, 8, 28),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    DENNIS_NOVIKOV: {
        'born_at': (1993, 11, 6),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    DI_WU: {
        'born_at': (1991, 9, 14),
        'height': 173,
        'forehand': RH,
        'backhand': THB,
    },
    DIEGO_SCHWARTZMAN: {
        'born_at': (1992, 8, 16),
        'height': 170,
        'forehand': RH,
        'backhand': THB,
    },
    DIMITAR_KUZMANOV: {
        'born_at': (1993, 7, 28),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    DOMINIC_THIEM: {
        'born_at': (1993, 9, 3),
        'height': 185,
        'forehand': RH,
        'backhand': OHB,
    },
    DOMINIK_KOEPFER: {
        'born_at': (1994, 4, 29),
        'height': 180,
        'forehand': LH,
        'backhand': THB,
    },
    DONALD_YOUNG: {
        'born_at': (1989, 7, 23),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    DUCKHEE_LEE: {
        'born_at': (1998, 5, 29),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    DUDI_SELA: {
        'born_at': (1985, 4, 4),
        'height': 175,
        'forehand': RH,
        'backhand': OHB,
    },
    DUSAN_LAJOVIC: {
        'born_at': (1990, 6, 30),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    DUSTIN_BROWN: {
        'born_at': (1984, 12, 8),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    EGOR_GERASIMOV: {
        'born_at': (1992, 11, 11),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    ELIAS_YMER: {
        'born_at': (1996, 4, 10),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ELLIOT_BENCHETRIT: {
        'born_at': (1998, 10, 2),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    EMIL_REINBERG: {
        'born_at': (1997, 4, 20),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    EMIL_RUUSUVUORI: {
        'born_at': (1999, 4, 2),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    EMILIO_GOMEZ: {
        'born_at': (1991, 11, 28),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    EMILIO_NAVA: {
        'born_at': (2001, 12, 2),
        'height': 183,
        'forehand': RH,
    },
    ENRIQUE_LOPEZ_PEREZ: {
        'born_at': (1991, 6, 3),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    ENZO_COUACAUD: {
        'born_at': (1995, 3, 1),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    ERGI_KIRKIN: {
        'born_at': (1999, 1, 27),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    ERNESTO_ESCOBEDO: {
        'born_at': (1996, 7, 4),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ERNESTS_GULBIS: {
        'born_at': (1988, 8, 30),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    EVAN_KING: {
        'born_at': (1992, 3, 25),
        'height': 185,
        'forehand': LH,
        'backhand': THB,
    },
    EVAN_SONG: {
        'born_at': (1992, 6, 7),
        'height': 178,
        'forehand': LH,
        'backhand': THB,
    },
    EVGENII_TIURNEV: {
        'born_at': (1997, 4, 8),
        'forehand': RH,
        'backhand': THB,
    },
    EVGENY_DONSKOY: {
        'born_at': (1990, 5, 9),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    EVGENY_KARLOVSKIY: {
        'born_at': (1994, 8, 7),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    FABIO_FOGNINI: {
        'born_at': (1987, 5, 24),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    FABRIZIO_ORNAGO: {
        'born_at': (1992, 4, 24),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    FACUNDO_ARGUELLO: {
        'born_at': (1992, 8, 4),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    FACUNDO_BAGNIS: {
        'born_at': (1990, 2, 27),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    FACUNDO_DIAZ_ACOSTA: {
        'born_at': (2000, 12, 15),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    FAJING_SUN: {
        'born_at': (1996, 10, 3),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    FEDERICO_CORIA: {
        'born_at': (1992, 3, 9),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    FEDERICO_DELBONIS: {
        'born_at': (1990, 10, 5),
        'height': 193,
        'forehand': LH,
        'backhand': THB,
    },
    FEDERICO_GAIO: {
        'born_at': (1992, 3, 5),
        'height': 180,
        'forehand': RH,
        'backhand': OHB,
    },
    FELICIANO_LOPEZ: {
        'born_at': (1981, 9, 20),
        'height': 188,
        'forehand': LH,
        'backhand': OHB,
    },
    FELIX_AUGER_ALIASSIME: {
        'born_at': (2000, 8, 8),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    FERNANDO_VERDASCO: {
        'born_at': (1983, 11, 15),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    FILIP_HORANSKY: {
        'born_at': (1993, 1, 7),
        'forehand': RH,
        'backhand': THB,
    },
    FILIP_KRAJINOVIC: {
        'born_at': (1992, 2, 27),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    FILIP_PELIWO: {
        'born_at': (1994, 1, 30),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    FILLIPPO_BALDI: {
        'born_at': (1996, 1, 10),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    FINN_TEARNEY: {
        'born_at': (1990, 9, 27),
        'height': 183,
        'forehand': RH,
    },
    FLORENT_DIEP: {
        'born_at': (1991, 9, 24),
        'height': 191,
        'forehand': RH,
    },
    FLORIAN_MAYER: {
        'born_at': (1983, 10, 5),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    FRANCES_TIAFOE: {
        'born_at': (1998, 1, 20),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    FRANCISCO_CERUNDOLO: {
        'born_at': (1998, 8, 13),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    FRANK_DANCEVIC: {
        'born_at': (1984, 9, 26),
        'height': 185,
        'forehand': RH,
        'backhand': OHB,
    },
    FRANKO_SKUGOR: {
        'born_at': (1987, 9, 20),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    FREDERICO_FERREIRA_SILVA: {
        'born_at': (1995, 3, 18),
        'forehand': LH,
        'backhand': THB,
    },
    GABRIEL_DONEV: {
        'born_at': (1996, 6, 29),
    },
    GAEL_MONFILS: {
        'born_at': (1986, 9, 1),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    GARRETT_JOHNS: {
        'born_at': (2000, 12, 17),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    GASTAO_ELIAS: {
        'born_at': (1990, 11, 24),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    GERALD_MELZER: {
        'born_at': (1990, 7, 13),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    GERARDO_LOPEZ_VILLASENOR: {
        'born_at': (1995, 5, 12),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    GIAN_MARCO_MORONI: {
        'born_at': (1998, 2, 13),
        'height': 185,
        'forehand': RH,
        'backhand': OHB,
    },
    GIANLUCA_MAGER: {
        'born_at': (1994, 12, 1),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    GIANLUIGI_QUINZI: {
        'born_at': (1996, 2, 1),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    GILLES_MULLER: {
        'born_at': (1983, 5, 9),
        'height': 193,
        'forehand': LH,
        'backhand': THB,
    },
    GILLES_SIMON: {
        'born_at': (1984, 12, 27),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    GLEB_SAKHAROV: {
        'born_at': (1988, 6, 10),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    GO_SOEDA: {
        'born_at': (1984, 9, 5),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    GONCALO_OLIVEIRA: {
        'born_at': (1995, 2, 17),
        'height': 185,
        'forehand': LH,
        'backhand': THB,
    },
    GONZALO_ESCOBAR: {
        'born_at': (1989, 1, 20),
        'height': 178,
        'forehand': LH,
        'backhand': THB,
    },
    GREGOIRE_BARRERE: {
        'born_at': (1994, 2, 16),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    GRIGOR_DIMITROV: {
        'born_at': (1991, 5, 16),
        'height': 191,
        'forehand': RH,
        'backhand': OHB,
    },
    GUIDO_ANDREOZZI: {
        'born_at': (1991, 8, 5),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    GUIDO_PELLA: {
        'born_at': (1990, 5, 17),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    GUILHERME_CLEZAR: {
        'born_at': (1992, 12, 31),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    GUILLERMO_GARCIA_LOPEZ: {
        'born_at': (1983, 6, 4),
        'height': 185,
        'forehand': RH,
        'backhand': OHB,
    },
    HARDOLD_MAYOT: {
        'born_at': (2002, 2, 4),
    },
    HARRY_BOURCHIER: {
        'born_at': (1996, 1, 24),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    HENRI_LAAKSONEN: {
        'born_at': (1992, 3, 31),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    HIROKI_MORIYA: {
        'born_at': (1990, 10, 16),
        'height': 168,
        'forehand': RH,
        'backhand': THB,
    },
    HORACIO_ZEBALLOS: {
        'born_at': (1985, 4, 27),
        'height': 188,
        'forehand': LH,
        'backhand': OHB,
    },
    HUBERT_HURKACZ: {
        'born_at': (1997, 2, 11),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    HUGO_DELLIEN: {
        'born_at': (1993, 6, 16),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    HUGO_GRENIER: {
        'born_at': (1996, 3, 23),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    HUGO_NYS: {
        'born_at': (1991, 2, 16),
        'height': 185,
        'forehand': RH,
        'backhand': OHB,
    },
    HUNTER_KOONTZ: {
    },
    HYEON_CHUNG: {
        'born_at': (1996, 5, 19),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    IGOR_ZELENAY: {
        'born_at': (1982, 10, 2),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    ILLYA_MARCHENKO: {
        'born_at': (1987, 9, 8),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ILYA_IVASHKA: {
        'born_at': (1994, 2, 24),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    IVAN_GAKHOV: {
        'born_at': (1996, 11, 4),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    IVAN_NEDELKO: {
        'born_at': (1986, 5, 12),
        'forehand': RH,
    },
    IVO_KARLOVIC: {
        'born_at': (1979, 2, 28),
        'height': 211,
        'forehand': RH,
        'backhand': OHB,
    },
    JABOR_AL_MUTAWA: {
        'born_at': (1994, 5, 27),
    },
    JACOPO_BERRETTINI: {
        'born_at': (1998, 11, 27),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    JACK_DRAPER: {
        'born_at': (2001, 12, 22),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    JACK_MINGJIE_LIN: {
        'born_at': (1999, 4, 15),
    },
    JACK_SOCK: {
        'born_at': (1992, 9, 24),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    JACOB_GRILLS: {
        'born_at': (1995, 6, 18),
    },
    JAKUB_PAUL: {
        'born_at': (1999, 3, 22),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    JAMES_DUCKWORTH: {
        'born_at': (1992, 1, 21),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JAMES_WARD: {
        'born_at': (1987, 2, 9),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JAMIE_CERRETANI: {
        'born_at': (1981, 10, 2),
        'height': 185,
        'forehand': LH,
        'backhand': OHB,
    },
    JAN_LENNARD_STRUFF: {
        'born_at': (1990, 4, 25),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    JANKO_TIPSAREVIC: {
        'born_at': (1984, 6, 22),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    JANNIK_SINNER: {
        'born_at': (2001, 8, 16),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JARED_DONALDSON: {
        'born_at': (1996, 10, 9),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JARED_HILTZIK: {
        'born_at': (1994, 7, 8),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    JASON_JUNG: {
        'born_at': (1989, 6, 15),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    JASON_KUBLER: {
        'born_at': (1993, 5, 19),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    JAUME_MUNAR: {
        'born_at': (1997, 5, 5),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JAVIER_BARRANCO_COSANO: {
        'born_at': (1998, 11, 17),
        'height': 175,
        'forehand': LH,
        'backhand': THB,
    },
    JAY_CLARKE: {
        'born_at': (1998, 7, 27),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JC_ARAGONE: {
        'born_at': (1995, 6, 28),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    JELLE_SELS: {
        'born_at': (1995, 8, 10),
        'height': 188,
        'forehand': RH,
        'backhand': OHB,
    },
    JENSON_BROOKSBY: {
        'born_at': (2000, 10, 26),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JEREMY_CHARDY: {
        'born_at': (1987, 2, 12),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JIRI_VESELY: {
        'born_at': (1993, 7, 10),
        'height': 198,
        'forehand': LH,
        'backhand': THB,
    },
    JJ_WOLF: {
        'born_at': (1998, 12, 21),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JO_WILFRIED_TSONGA: {
        'born_at': (1985, 4, 17),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JOAO_DOMINGUES: {
        'born_at': (1993, 10, 5),
        'forehand': RH,
        'backhand': THB,
    },
    JOAO_MENEZES: {
        'born_at': (1996, 12, 17),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    JOAO_SOUSA: {
        'born_at': (1989, 3, 30),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    JOHAN_NIKLES: {
        'born_at': (1997, 3, 23),
        'height': 170,
        'forehand': RH,
        'backhand': THB,
    },
    JOHANNES_HAERTEIS: {
        'born_at': (1996, 2, 22),
        'height': 193,
        'forehand': LH,
        'backhand': THB,
    },
    JOHN_HALLQUIST_LITHEN: {
        'born_at': (2001, 12, 3),
    },
    JOHN_ISNER: {
        'born_at': (1985, 4, 26),
        'height': 208,
        'forehand': RH,
        'backhand': THB,
    },
    JOHN_MCNALLY: {
        'born_at': (1998, 10, 18),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JOHN_MILLMAN: {
        'born_at': (1989, 6, 14),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JOHN_PATRICK_SMITH: {
        'born_at': (1989, 1, 24),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    JONATHAN_EYSSERIC: {
        'born_at': (1990, 5, 27),
        'height': 180,
        'forehand': LH,
        'backhand': THB,
    },
    JORDAN_THOMPSON: {
        'born_at': (1994, 4, 20),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JORGE_PLANS: {
        'born_at': (2002, 1, 28),
    },
    JOZEF_KOVALIK: {
        'born_at': (1992, 11, 4),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JUAN_ALEJANDRO_HERNANDEZ: {
        'born_at': (1999, 6, 23),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    JUAN_BAUTISTA_OTEGUI: {
        'born_at': (1999, 2, 23),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    JUAN_IGNACIO_BATALLA: {
        'forehand': LH,
        'backhand': THB,
    },
    JUAN_IGNACIO_LONDERO: {
        'born_at': (1993, 8, 15),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    JUAN_MARTIN_DEL_POTRO: {
        'born_at': (1988, 9, 23),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    JUAN_PABLO_FICOVICH: {
        'born_at': (1997, 1, 24),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    JIE_CUI: {
        'born_at': (1998, 1, 24),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JULIAN_LENZ: {
        'born_at': (1993, 2, 17),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JULIAN_OCLEPPO: {
        'born_at': (1997, 8, 1),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    JULIEN_BENNETEAU: {
        'born_at': (1981, 12, 20),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    JULIAN_ZLOBINSKY: {
        'born_at': (1996, 1, 8),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    JURGEN_MELZER: {
        'born_at': (1981, 5, 22),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    JURGEN_ZOPP: {
        'born_at': (1988, 3, 29),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    JURIJ_RODIONOV: {
        'born_at': (1995, 5, 16),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    KAICHI_UCHIDA: {
        'born_at': (1994, 8, 23),
        'forehand': RH,
    },
    KAMIL_MAJCHRZAK: {
        'born_at': (1996, 1, 13),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    KAREN_KHACHANOV: {
        'born_at': (1996, 5, 21),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    KARIM_MOHAMED_MAAMOUN: {
        'born_at': (1991, 4, 9),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    KARL_FRIBERG: {
        'born_at': (1999, 3, 25),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    KARL_POLING: {
        'born_at': (1999, 8, 4),
        'height': 185,
        'forehand': LH,
    },
    KARUE_SELL: {
        'born_at': (1993, 11, 13),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    KEI_NISHIKORI: {
        'born_at': (1989, 12, 29),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    KENNY_DE_SCHEPPER: {
        'born_at': (1987, 5, 29),
        'height': 203,
        'forehand': LH,
        'backhand': OHB,
    },
    KEVIN_ANDERSON: {
        'born_at': (1986, 5, 18),
        'height': 203,
        'forehand': RH,
        'backhand': THB,
    },
    KEVIN_KING: {
        'born_at': (1991, 2, 28),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    KEVIN_KRAWIETZ: {
        'born_at': (1992, 1, 24),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    KIMMER_COPPEJANS: {
        'born_at': (1994, 2, 7),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    KIRANPAL_PANNU: {
        'born_at': (1997, 1, 7),
    },
    KYLE_EDMUND: {
        'born_at': (1995, 1, 8),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    LAMINE_OUAHAB: {
        'born_at': (1984, 12, 22),
        'height': 185,
        'forehand': RH,
    },
    LASLO_DJERE: {
        'born_at': (1995, 6, 2),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    LAURYNAS_GRIGELIS: {
        'born_at': (1991, 8, 14),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    LEONARDO_MAYER: {
        'born_at': (1987, 5, 15),
        'height': 191,
        'forehand': RH,
        'backhand': OHB,
    },
    LIAM_BROADY: {
        'born_at': (1994, 1, 4),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    LLOYD_HARRIS: {
        'born_at': (1997, 2, 24),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    LORENZO_GIUSTINO: {
        'born_at': (1991, 9, 10),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    LORENZO_MUSETTI: {
        'born_at': (2002, 3, 3),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    LORENZO_SONEGO: {
        'born_at': (1995, 5, 11),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    LOUIS_WESSELS: {
        'born_at': (1998, 8, 27),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    LUCA_MARGAROLI: {
        'born_at': (1992, 2, 15),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    LUCA_VANNI: {
        'born_at': (1985, 6, 4),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    LUCAS_CATARINA: {
        'born_at': (1996, 8, 26),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    LUCAS_GOMEZ: {
        'born_at': (1995, 8, 11),
        'height': 178,
        'forehand': LH,
        'backhand': THB,
    },
    LUCAS_MIEDLER: {
        'born_at': (1996, 6, 21),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    LUCAS_POUILLE: {
        'born_at': (1994, 2, 23),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    LUIS_PATINO: {
        'born_at': (1993, 10, 6),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    LUKAS_LACKO: {
        'born_at': (1987, 11, 3),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    LUKAS_ROSOL: {
        'born_at': (1985, 7, 24),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    LUKE_SAVILLE: {
        'born_at': (1994, 1, 2),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    MACKENZIE_MCDONALD: {
        'born_at': (1995, 4, 16),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    MALEK_JAZIRI: {
        'born_at': (1984, 1, 20),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    MANUEL_GUINARD: {
        'born_at': (1995, 11, 15),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    MARC_ANDREA_HUESLER: {
        'born_at': (1996, 6, 24),
        'height': 196,
        'forehand': LH,
        'backhand': THB,
    },
    MARC_POLMANS: {
        'born_at': (1997, 5, 2),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    MARCEL_GRANOLLERS: {
        'born_at': (1986, 4, 12),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    MARCELO_AREVALO: {
        'born_at': (1990, 10, 17),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    MARCELO_TOMAS_BARRIOS_VERA: {
        'born_at': (1997, 12, 10),
        'forehand': RH,
        'backhand': THB,
    },
    MARCO_CECCHINATO: {
        'born_at': (1992, 9, 30),
        'height': 185,
        'forehand': RH,
        'backhand': OHB,
    },
    MARCO_TRUNGELLITI: {
        'born_at': (1990, 1, 31),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    MARCOS_BAGHDATIS: {
        'born_at': (1985, 6, 17),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    MARCOS_GIRON: {
        'born_at': (1993, 7, 24),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    MARIN_CILIC: {
        'born_at': (1988, 9, 28),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    MARIO_VILELLA_MARTINEZ: {
        'born_at': (1995, 7, 3),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    MARIUS_COPIL: {
        'born_at': (1990, 10, 17),
        'height': 193,
        'forehand': RH,
        'backhand': OHB,
    },
    MARKO_MILADINOVIC: {
        'born_at': (2000, 12, 7),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    MARKUS_ERIKSSON: {
        'born_at': (1989, 11, 29),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    MARTIN_KLIZAN: {
        'born_at': (1989, 7, 11),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    MARTIN_REDLICKI: {
        'born_at': (1995, 8, 24),
        'height': 196,
        'forehand': LH,
        'backhand': THB,
    },
    MARTON_FUCSOVICS: {
        'born_at': (1992, 2, 8),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    MARVIN_MOELLER: {
        'born_at': (1999, 1, 18),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    MATE_VALKUSZ: {
        'born_at': (1998, 8, 13),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    MATEUS_ALVES: {
        'born_at': (1997, 6, 18),
    },
    MATTEO_BERRETTINI: {
        'born_at': (1996, 4, 12),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    MATTEO_DONATI: {
        'born_at': (1995, 2, 28),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    MATTEO_VIOLA: {
        'born_at': (1987, 7, 7),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    MATTHEW_EBDEN: {
        'born_at': (1987, 11, 26),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    MATTHIAS_BACHINGER: {
        'born_at': (1987, 4, 2),
        'height': 188,
        'forehand': RH,
    },
    MATTHIAS_HAIM: {
        'born_at': (1998, 1, 11),
        'height': 196,
        'forehand': RH,
        'backhand': OHB,
    },
    MATS_MORAING: {
        'born_at': (1992, 6, 20),
        'height': 198,
        'forehand': LH,
        'backhand': THB,
    },
    MAX_PURCELL: {
        'born_at': (1998, 4, 3),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    MAVERICK_BANES: {
        'born_at': (1992, 4, 10),
        'forehand': RH,
    },
    MAXIME_CRESSY: {
        'born_at': (1997, 5, 8),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    MAXIME_JANVIER: {
        'born_at': (1996, 10, 18),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    MAXIMILIAN_MARTERER: {
        'born_at': (1995, 6, 15),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    MAXIMILIAN_NEUCHRIST: {
        'born_at': (1991, 7, 22),
        'forehand': RH,
        'backhand': THB,
    },
    MICHAEL_MMOH: {
        'born_at': (1998, 1, 10),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    MIGUEL_ANGEL_REYES_VARELA: {
        'born_at': (1987, 6, 21),
        'height': 175,
        'forehand': RH,
        'backhand': OHB,
    },
    MIKAEL_TORPEGAARD: {
        'born_at': (1994, 5, 8),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    MIKAEL_YMER: {
        'born_at': (1998, 9, 9),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    MIKHAIL_KUKUSHKIN: {
        'born_at': (1987, 12, 26),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    MIKHAIL_YOUZHNY: {
        'born_at': (1982, 6, 25),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    MILIAAN_NIESTEN: {
        'born_at': (1988, 6, 27),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    MILJAN_ZEKIC: {
        'born_at': (1988, 7, 12),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    MILOS_RAONIC: {
        'born_at': (1990, 12, 27),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    MIOMIR_KECMANOVIC: {
        'born_at': (1999, 8, 31),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    MIRZA_BASIC: {
        'born_at': (1991, 7, 12),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    MISCHA_ZVEREV: {
        'born_at': (1987, 8, 22),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    MITCHELL_KRUEGER: {
        'born_at': (1994, 1, 12),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    MOHAMED_SAFWAT: {
        'born_at': (1990, 9, 19),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    MORITZ_THIEM: {
        'born_at': (1999, 12, 8),
        'forehand': RH,
    },
    MOUSA_SHANAN_ZAYED: {
        'born_at': (1994, 3, 9),
    },
    MUBARAK_SHANNAN_ZAYID: {
        'born_at': (1995, 4, 14),
        'forehand': RH,
        'backhand': THB,
    },
    NATAN_RODRIGUES: {
        'born_at': (2002, 2, 2),
    },
    NICHOLAS_REYES: {
        'born_at': (1995, 1, 17),
        'height': 188,
        'forehand': RH,
        'backhand': OHB,
    },
    NICK_KYRGIOS: {
        'born_at': (1995, 4, 27),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    NICOLA_KUHN: {
        'born_at': (2000, 3, 20),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    NICOLAS_ALMAGRO: {
        'born_at': (1985, 8, 21),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    NICOLAS_JARRY: {
        'born_at': (1995, 10, 11),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    NICOLAS_MAHUT: {
        'born_at': (1982, 1, 21),
        'height': 191,
        'forehand': RH,
        'backhand': OHB,
    },
    NIK_RAZBORSEK: {
        'born_at': (1993, 10, 4),
        'height': 173,
        'forehand': LH,
        'backhand': THB,
    },
    NIKLAS_GUTTAU: {
        'born_at': (2000, 1, 3),
        'height': 178,
        'forehand': LH,
        'backhand': THB,
    },
    NIKOLA_MILOJEVIC: {
        'born_at': (1995, 6, 19),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    NIKOLOZ_BASILASHVILI: {
        'born_at': (1992, 2, 23),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    NINO_SERDARUSIC: {
        'born_at': (1996, 12, 13),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    NOAH_RUBIN: {
        'born_at': (1996, 2, 21),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    NORBERT_GOMBOS: {
        'born_at': (1990, 8, 13),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    NOVAK_DJOKOVIC: {
        'born_at': (1987, 5, 22),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    ORIOL_ROCA_BATALLA: {
        'born_at': (1993, 4, 30),
        'height': 173,
        'forehand': RH,
        'backhand': OHB,
    },
    OSCAR_OTTE: {
        'born_at': (1993, 7, 16),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    PABLO_ANDUJAR: {
        'born_at': (1986, 1, 23),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    PABLO_CARRENO_BUSTA: {
        'born_at': (1991, 7, 12),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    PABLO_CUEVAS: {
        'born_at': (1986, 1, 1),
        'height': 180,
        'forehand': RH,
        'backhand': OHB,
    },
    PAOLO_LORENZI: {
        'born_at': (1981, 12, 15),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    PATRICK_KYPSON: {
        'born_at': (1999, 10, 28),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    PAUL_JUBB: {
        'born_at': (1999, 10, 31),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    PEDJA_KRSTIN: {
        'born_at': (1994, 9, 3),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    PEDRO_CACHIN: {
        'born_at': (1995, 4, 12),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    PEDRO_MARTINEZ: {
        'born_at': (1997, 4, 26),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    PEDRO_SAKAMOTO: {
        'born_at': (1993, 6, 29),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    PEDRO_SOUSA: {
        'born_at': (1988, 5, 27),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    PETER_GOJOWCZYK: {
        'born_at': (1989, 7, 15),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    PETER_POLANSKY: {
        'born_at': (1988, 6, 15),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    PETER_TOREBKO: {
        'born_at': (1988, 2, 10),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    PETROS_CHRYSOCHOS: {
        'born_at': (1996, 4, 8),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    PHILIPP_KOHLSCHREIBER: {
        'born_at': (1983, 10, 16),
        'height': 178,
        'forehand': RH,
        'backhand': OHB,
    },
    PHILIPP_OSWALD: {
        'born_at': (1986, 1, 23),
        'height': 201,
        'forehand': RH,
        'backhand': OHB,
    },
    PIERRE_HUGUES_HERBERT: {
        'born_at': (1991, 3, 18),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    PRAJNESH_GUNNESWARAN: {
        'born_at': (1989, 11, 12),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    PRESTON_BROWN: {
        'born_at': (2001, 8, 23),
        'height': 198,
        'forehand': LH,
        'backhand': THB,
    },
    QUENTIN_HALYS: {
        'born_at': (1996, 10, 26),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    RADU_ALBOT: {
        'born_at': (1989, 11, 11),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    RAFAEL_MATOS: {
        'born_at': (1996, 1, 6),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    RAFAEL_NADAL: {
        'born_at': (1986, 6, 3),
        'height': 185,
        'forehand': LH,
        'backhand': THB,
    },
    RAMKUMAR_RAMANATHAN: {
        'born_at': (1994, 11, 8),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    RAPHAEL_BALTENSPERGER: {
        'born_at': (1997, 12, 18),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    RAYANE_ROUMANE: {
        'born_at': (2000, 9, 11),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    RAYMOND_SARMIENTO: {
        'born_at': (1992, 7, 24),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    REILLY_OPELKA: {
        'born_at': (1997, 8, 28),
        'height': 211,
        'forehand': RH,
        'backhand': THB,
    },
    RENTA_TOKUDA: {
        'born_at': (1998, 3, 29),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    RENZO_OLIVO: {
        'born_at': (1992, 3, 15),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    RICARDAS_BERANKIS: {
        'born_at': (1990, 6, 21),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    RICARDO_OJEDA_LARA: {
        'born_at': (1993, 1, 26),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    RICCARDO_BALZERANI: {
        'born_at': (1998, 10, 25),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    RICHARD_GASQUET: {
        'born_at': (1986, 6, 18),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    RIGELE_TE: {
        'born_at': (1997, 10, 9),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    ROBERT_MACIAG: {
    },
    ROBERTO_BAUTISTA_AGUT: {
        'born_at': (1988, 4, 14),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ROBERTO_CARBALLES_BAENA: {
        'born_at': (1993, 3, 23),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ROBERTO_CID_SUBERVI: {
        'born_at': (1993, 8, 30),
        'height': 193,
        'forehand': RH,
    },
    ROBERTO_MARCORA: {
        'born_at': (1989, 8, 30),
        'height': 193,
        'forehand': RH,
        'backhand': OHB,
    },
    ROBERTO_ORTEGA_OLMEDO: {
        'born_at': (1991, 4, 30),
        'height': 168,
        'forehand': RH,
        'backhand': OHB,
    },
    ROBERTO_QUIROZ: {
        'born_at': (1992, 2, 23),
        'height': 193,
        'forehand': LH,
        'backhand': THB,
    },
    ROBIN_HAASE: {
        'born_at': (1987, 4, 6),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    ROGER_FEDERER: {
        'born_at': (1981, 8, 8),
        'height': 185,
        'forehand': RH,
        'backhand': OHB,
    },
    ROGERIO_DUTRA_SILVA: {
        'born_at': (1984, 2, 5),
        'height': 178,
        'forehand': RH,
        'backhand': OHB,
    },
    ROMAIN_ARNEODO: {
        'born_at': (1992, 8, 4),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    ROMAN_SAFIULLIN: {
        'born_at': (1997, 8, 7),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    ROY_SMITH: {
        'born_at': (1998, 9, 13),
        'height': 191,
        'forehand': LH,
        'backhand': THB,
    },
    RUBEN_BEMELMANS: {
        'born_at': (1988, 1, 14),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    RUBIN_STATHAM: {
        'born_at': (1987, 4, 25),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    RUDOLF_MOLLEKER: {
        'born_at': (2000, 10, 26),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    RUNHAO_HUA: {
        'born_at': (1996, 3, 6),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    RYAN_HARRISON: {
        'born_at': (1992, 5, 7),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    RYAN_NIJBOER: {
        'born_at': (1999, 7, 28),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    RYAN_SHANE: {
        'born_at': (1994, 4, 15),
        'height': 193,
        'forehand': RH,
        'backhand': OHB,
    },
    SAKETH_MYNENI: {
        'born_at': (1987, 10, 19),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    SALVATORE_CARUSO: {
        'born_at': (1992, 12, 15),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    SAM_QUERREY: {
        'born_at': (1987, 10, 7),
        'height': 198,
        'forehand': RH,
        'backhand': THB,
    },
    SANDRO_EHRAT: {
        'born_at': (1991, 4, 18),
        'height': 180,
        'forehand': RH,
    },
    SANDRO_KOPP: {
        'born_at': (2000, 5, 26),
        'forehand': RH,
    },
    SANTIAGO_GIRALDO: {
        'born_at': (1987, 11, 27),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    SARP_AGABIGUN: {
        'born_at': (1997, 6, 12),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    SASI_KUMAR_MUKUND: {
        'born_at': (1997, 1, 14),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    SCOTT_GRIEKSPOOR: {
        'born_at': (1991, 1, 10),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    SEBASTIAN_KORDA: {
        'born_at': (2000, 7, 5),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    SEBASTIAN_OFNER: {
        'born_at': (1996, 5, 12),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    SERGIO_GUTIERREZ_FERROL: {
        'born_at': (1989, 3, 5),
        'forehand': RH,
    },
    SERGIY_STAKHOVSKY: {
        'born_at': (1986, 1, 6),
        'height': 193,
        'forehand': RH,
        'backhand': OHB,
    },
    SIMON_CARR: {
        'born_at': (1999, 11, 7),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    SIMONE_BOLELLI: {
        'born_at': (1985, 10, 8),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    SKANDER_MANSOURI: {
        'born_at': (1995, 7, 23),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    SOONWOO_KWON: {
        'born_at': (1997, 12, 2),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    STAN_WAWRINKA: {
        'born_at': (1985, 3, 28),
        'height': 183,
        'forehand': RH,
        'backhand': OHB,
    },
    STEFAN_KOZLOV: {
        'born_at': (1998, 2, 1),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    STEFANO_NAPOLITANO: {
        'born_at': (1995, 4, 11),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    STEFANO_TRAVAGLIA: {
        'born_at': (1991, 12, 28),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    STEFANOS_TSITSIPAS: {
        'born_at': (1998, 8, 12),
        'height': 193,
        'forehand': RH,
        'backhand': OHB,
    },
    STEPHANE_ROBERT: {
        'born_at': (1980, 5, 17),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    STEVE_DARCIS: {
        'born_at': (1984, 3, 13),
        'height': 175,
        'forehand': RH,
        'backhand': OHB,
    },
    STEVE_JOHNSON: {
        'born_at': (1989, 12, 24),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    STEVEN_DIEZ: {
        'born_at': (1991, 3, 17),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    STRONG_KIRCHHEIMER: {
        'born_at': (1995, 4, 26),
        'height': 185,
        'forehand': RH,
    },
    SUMIT_NAGAL: {
        'born_at': (1997, 8, 16),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    ZACHARY_SVAJDA: {
        'born_at': (2002, 11, 29),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    TAHA_BAADI: {
        'born_at': (2001, 7, 19),
        'forehand': RH,
    },
    TAKANYI_GARANGANGA: {
        'born_at': (1990, 9, 6),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    TALLON_GRIEKSPOOR: {
        'born_at': (1996, 7, 2),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    TARO_DANIEL: {
        'born_at': (1993, 1, 27),
        'height': 191,
        'forehand': RH,
        'backhand': THB,
    },
    TATSUMA_ITO: {
        'born_at': (1988, 5, 18),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    TAYLOR_FRITZ: {
        'born_at': (1997, 10, 28),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    TENNYS_SANDGREN: {
        'born_at': (1991, 7, 22),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    TEYMURAZ_GABASHVILI: {
        'born_at': (1985, 5, 23),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    THAI_SON_KWIATKOWSKI: {
        'born_at': (1995, 2, 13),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    THANASI_KOKKINAKIS: {
        'born_at': (1996, 4, 10),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    THIAGO_MONTEIRO: {
        'born_at': (1994, 5, 31),
        'height': 183,
        'forehand': LH,
        'backhand': THB,
    },
    THIAGO_SEYBOTH_WILD: {
        'born_at': (2000, 3, 10),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    THIEMO_DE_BAKKER: {
        'born_at': (1988, 9, 19),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    THOMAS_FABBIANO: {
        'born_at': (1989, 5, 26),
        'height': 173,
        'forehand': RH,
        'backhand': THB,
    },
    THOMAZ_BELLUCCI: {
        'born_at': (1987, 12, 30),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    TIGRE_HANK: {
        'born_at': (1991, 9, 30),
        'height': 188,
        'forehand': LH,
    },
    TIM_PUETZ: {
        'born_at': (1987, 11, 19),
        'height': 185,
        'forehand': RH,
    },
    TIM_SMYCZEK: {
        'born_at': (1987, 12, 30),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    TOBIAS_KAMKE: {
        'born_at': (1986, 5, 21),
        'height': 178,
        'forehand': RH,
        'backhand': THB,
    },
    TOM_FAWCETT: {
        'born_at': (1995, 10, 18),
        'height': 196,
        'forehand': RH,
    },
    TOMAS_BERDYCH: {
        'born_at': (1985, 9, 17),
        'height': 196,
        'forehand': RH,
        'backhand': THB,
    },
    TOMISLAV_BRKIC: {
        'born_at': (1990, 3, 9),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    TOMMY_PAUL: {
        'born_at': (1997, 5, 17),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    TOMMY_ROBREDO: {
        'born_at': (1982, 5, 1),
        'height': 180,
        'forehand': RH,
        'backhand': OHB,
    },
    TRENT_BRYDE: {
        'born_at': (1999, 8, 24),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    TRISTAN_LAMASINE: {
        'born_at': (1993, 3, 5),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    UGO_HUMBERT: {
        'born_at': (1998, 6, 26),
        'height': 188,
        'forehand': LH,
        'backhand': THB,
    },
    ULADZIMIR_IGNATIK: {
        'born_at': (1990, 7, 14),
        'height': 183,
        'forehand': RH,
    },
    ULISES_BLANCH: {
        'born_at': (1998, 3, 25),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    VACLAV_SAFRANEK: {
        'born_at': (1994, 5, 20),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    VASEK_POSPISIL: {
        'born_at': (1990, 6, 23),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    VICTOR_ESTRELLA_BURGOS: {
        'born_at': (1980, 8, 2),
        'height': 170,
        'forehand': RH,
        'backhand': OHB,
    },
    VIKTOR_GALOVIC: {
        'born_at': (1990, 9, 19),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    VIKTOR_TROICKI: {
        'born_at': (1986, 2, 10),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    VINCENT_MILLOT: {
        'born_at': (1986, 1, 30),
        'height': 173,
        'forehand': LH,
        'backhand': THB,
    },
    XIN_GAO: {
        'born_at': (1994, 5, 12),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    Y_BAI: {
    },
    YANN_MARTI: {
        'born_at': (1988, 6, 7),
        'height': 173,
        'forehand': RH,
        'backhand': THB,
    },
    YANKI_EREL: {
        'born_at': (2000, 9, 25),
        'forehand': LH,
        'backhand': THB,
    },
    YANNICK_HANFMANN: {
        'born_at': (1991, 11, 13),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    YANNICK_MADEN: {
        'born_at': (1989, 10, 28),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    YANNICK_MERTENS: {
        'born_at': (1987, 6, 25),
        'height': 188,
        'forehand': RH,
    },
    YASUTAKA_UCHIYAMA: {
        'born_at': (1992, 8, 5),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    YECONG_HE: {
        'born_at': (1994, 2, 15),
        'height': 180,
        'forehand': RH,
    },
    YIBING_WU: {
        'born_at': (1999, 10, 14),
        'height': 183,
        'forehand': RH,
        'backhand': THB,
    },
    YOSHIHITO_NISHIOKA: {
        'born_at': (1995, 9, 27),
        'height': 170,
        'forehand': LH,
        'backhand': THB,
    },
    YOSUKE_WATANUKI: {
        'born_at': (1998, 4, 12),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
    YUICHI_SUGITA: {
        'born_at': (1988, 9, 18),
        'height': 175,
        'forehand': RH,
        'backhand': THB,
    },
    YUKI_BHAMBRI: {
        'born_at': (1992, 7, 4),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    YUSUKE_TAKAHASHI: {
        'born_at': (1997, 10, 17),
        'height': 170,
        'forehand': RH,
        'backhand': THB,
    },
    ZANE_KHAN: {
    },
    ZDENEK_KOLAR: {
        'born_at': (1996, 10, 9),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ZE_ZHANG: {
        'born_at': (1990, 7, 4),
        'height': 188,
        'forehand': RH,
        'backhand': THB,
    },
    ZHAO_ZHAO: {
    },
    ZHE_LI: {
        'born_at': (1986, 9, 20),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ZHIZHEN_ZHANG: {
        'born_at': (1996, 10, 16),
        'height': 193,
        'forehand': RH,
        'backhand': THB,
    },
    ZIHAO_XIA: {
        'born_at': (1997, 1, 30),
        'forehand': RH,
    },
    ZIZOU_BERGS: {
        'born_at': (1999, 6, 3),
        'height': 185,
        'forehand': RH,
        'backhand': THB,
    },
    ZSOMBOR_PIROS: {
        'born_at': (1999, 10, 13),
        'height': 180,
        'forehand': RH,
        'backhand': THB,
    },
}


avg_born_at = get_default_metas()
